FROM python:3.11.2

WORKDIR /Backend

COPY requirements.txt /Backend/

RUN pip install -U pip
RUN pip install -r requirements.txt 

COPY . /Backend/

EXPOSE 8000

CMD [ "gunicorn" , "foodd.wsgi:application" , "--bind", "0.0.0.0:8000"]



