FROM python:3.11.2

WORKDIR /Backend

COPY requirements.txt /Backend/

RUN pip install -U pip
RUN pip install -r requirements.txt 

COPY . /foodd/

EXPOSE 8000

CMD [ "gunicorn" , "A.wsgi" ,":8000"]



