# Generated by Django 5.0.3 on 2024-03-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='Media/category')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('desc', models.TextField(max_length=2500)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='Media/category/food')),
                ('category', models.ManyToManyField(blank=True, to='home.category')),
            ],
        ),
    ]
